import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import Exercise from "@/components/Exercise";
import Footer from "@/components/Footer";
import { getSortedWorkoutsData } from "@/lib/workouts";
import Link from "next/link";
import Cards from "@/components/Cards";

export const getStaticProps = () => {
  const allWorkoutsData = getSortedWorkoutsData();

  return {
    props: {
      allWorkoutsData,
    },
  };
};

export default function Home({ allWorkoutsData }) {
  return (
    <>
      <Head>
        <title>GYM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <main className={styles.main}>
          <div className="container">
            <section className="introduction">
              <h1 className="main-title">Welcome to your GYM</h1>
              <h2 className="main-subtitle">Find the healthy way</h2>
            </section>
            <section className="programs">
              <span className="line"></span>
              <h2 className="title">Popular Workouts</h2>
              <Cards workouts={allWorkoutsData} />
            </section>
            <section className="exercises">
              <span className="line"></span>
              <h2 className="title">Popular Exercises</h2>
              <div className="exercises-cards">
                <Exercise />
                <Exercise />
                <Exercise />

                <ul>
                  {allWorkoutsData.map((workoutData) => {
                    return (
                      <li key={workoutData.id}>
                        <Link href={`/workouts/${workoutData.id}`}>
                          {workoutData.title}
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </section>
          </div>
        </main>
        <Footer />
      </Layout>
    </>
  );
}
