import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Layout from "@/components/Layout";
import Exercise from "@/components/Exercise";
import Footer from "@/components/Footer";
import { getSortedWorkoutsData } from "@/lib/workouts";
import Cards from "@/components/Cards";
import { getSortedProgramsData } from "@/lib/programs";

export const getStaticProps = () => {
  const allWorkoutsData = getSortedWorkoutsData();
  const allProgramsData = getSortedProgramsData();

  return {
    props: {
      allWorkoutsData,
      allProgramsData,
    },
  };
};

export default function Home({ allWorkoutsData, allProgramsData }) {
  const firstWorkouts = allWorkoutsData.filter((workout, i) => i <= 5);
  const firstPrograms = allProgramsData.filter((program, i) => i < 4);
  return (
    <>
      <Head>
        <title>GYM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <main className={styles.main}>
          <div className="container">
            <section className="introduction">
              <h1 className="main-title">Welcome to your GYM</h1>
              <h2 className="main-subtitle">Find the healthy way</h2>
            </section>
            <section className="programs">
              <span className="line"></span>
              <h2 className="title">Popular Exercises</h2>
              <Cards workouts={firstWorkouts} />
            </section>
            <section className="exercises">
              <span className="line"></span>
              <h2 className="title">Popular Programs</h2>
              <ul className="exercises-cards">
                {firstPrograms.map((programData) => (
                  <li key={programData.id}>
                    <Exercise program={programData} />
                  </li>
                ))}
              </ul>
            </section>
          </div>
        </main>
        <Footer />
      </Layout>
    </>
  );
}
